prgrms-web-devcourse/Team_i6_comepet_BE

.github/workflows/gradle.yml
=> Gradle CI 문서 작성

src/main/java/com/pet/common/config/SecurityConfig.java, src/main/java/com/pet/common/exception/ExceptionHandler.java, src/main/java/com/pet/common/response/ApiResponse.java, src/main/java/com/pet/common/response/ErrorResponse.java, src/main/java/com/pet/common/util/SampleUtil.java, src/main/java/com/pet/domains/BaseEntity.java, src/main/java/com/pet/domains/account/controller/AccountController.java, src/main/java/com/pet/domains/account/domain/Account.java, src/main/java/com/pet/domains/account/dto/request/SampleRequest.java, src/main/java/com/pet/domains/account/dto/response/SampleResponse.java, src/main/java/com/pet/domains/account/repository/AccountReposiotry.java, src/main/java/com/pet/domains/account/service/AccountService.java
=> chore: 도메인 패키지 스켈레톤 코드

.gitattributes, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, build.gradle, src/main/java/com/pet/common/config/SecurityConfig.java, src/main/java/com/pet/common/exception/ExceptionHandler.java, src/main/java/com/pet/common/response/ApiResponse.java, src/main/java/com/pet/common/response/ErrorResponse.java, src/main/java/com/pet/common/util/SampleUtil.java, src/main/java/com/pet/domains/BaseEntity.java, src/main/java/com/pet/domains/account/controller/AccountController.java, src/main/java/com/pet/domains/account/domain/Account.java, src/main/java/com/pet/domains/account/dto/request/SampleRequest.java, src/main/java/com/pet/domains/account/dto/response/SampleResponse.java, src/main/java/com/pet/domains/account/repository/AccountReposiotry.java, src/main/java/com/pet/domains/account/service/AccountService.java
close #13 
- 설명 : 체크 스타일에 따라 개행은 LF로 되도록 깃 정책 설정
- .gittattributes 추가
- 이슈 & PR 템플릿의 체크박스 수정
- 코드 리포맷팅
- https://naver.github.io/hackday-conventions-java/
- https://www.lesstif.com/gitbook/git-crlf-20776404.html
- https://stackoverflow.com/questions/9976986/force-lf-eol-in-git-repo-and-working-copy
=> [CP-13] chore : 체크 스타일 개행 컨벤션을 위한 git 설정 추가

src/main/java/com/pet/domains/bookmark/domain/MissingPostBookmark.java, src/main/java/com/pet/domains/bookmark/domain/ShelterPostBookmark.java, src/main/java/com/pet/domains/post/domain/NeuteredType.java, src/main/java/com/pet/domains/post/domain/ShelterPost.java, src/main/java/com/pet/domains/post/domain/ShelterSexType.java, src/main/java/com/pet/domains/statistics/domain/PostStatistics.java
close #17 
- 설명 : 보호소 유기 게시글(ShelterPost), 게시글 통계(PostStatistics), 실종/보호 게시글 북마크(MissingPostBookmark), 보호소 유기 게시글 북마크(ShelterPostBookmark)
- change
- 엔티티매핑이 필요한 객체는 일단 주석으로 표시해두었습니다.
- columnDefinition을 사용해 설계한 테이블과 타입이 맞도록 지정하였습니다.
=> [CP-17] feat: 엔티티 클래스 생성2

.github/workflows/sonar.yml, build.gradle
close #23
- 설명 : 소나 클라우드 연동하기
- 빌드 yml & 그레이들 수정 했습니다.
=> [CP-23] chore: 소나 클라우드 세팅

src/main/java/com/pet/common/config/JpaAuditingConfig.java, src/main/java/com/pet/domains/BaseEntity.java, src/main/java/com/pet/domains/DeletableEntity.java, src/main/java/com/pet/domains/account/domain/Account.java, src/main/java/com/pet/domains/account/domain/Notification.java, src/main/java/com/pet/domains/account/repository/AccountRepository.java, src/main/java/com/pet/domains/area/domain/City.java, src/main/java/com/pet/domains/area/domain/InterestArea.java, src/main/java/com/pet/domains/area/domain/Town.java, src/main/java/com/pet/domains/comment/domain/Comment.java
close #15
- 설명 : 이슈의 엔티티 클래스 추가했습니다.
- BaseEntity, DeletableEntity 추가
- auditing config 클래스 추가
- 따로 생각해두신 soft delete 구현 방법 계시분 의견주세요~!
=> [CP-15] feat: 엔티티 클래스 생성1

src/main/java/com/pet/domains/account/domain/Notification.java, src/main/java/com/pet/domains/area/domain/InterestArea.java, src/main/java/com/pet/domains/area/domain/Town.java, src/main/java/com/pet/domains/comment/domain/Comment.java, src/main/resources/application.yaml
close #29
- 설명 : 엔티티 연관관계 설정
- change
=> [CP-29] 엔티티 연관관계 추가3

.github/workflows/sonar.yml, build.gradle
close #34 
- 설명 : xml 리포트 자체로 분석하고 있는 것 같아서 마지막 테스트입니다!
- xml 리포트 생성 안하도록 수정
- 작업 이름 수정
=> [CP-34 ] 소나 클라우드 자코코 연동해제2

.github/workflows/deploy.yml
close #36 
- 설명 : 배포를 위해 S3로 jar 파일을 zip파일로 압축하여 전송하는 트리거 작성
- change
트리거 테스트 필요
=> [CP-36] chore: s3 Code Deploy 트리거 생성

.github/workflows/gradle.yml, src/main/java/com/pet/Application.java
close #38 
- 설명 : s3 jar zip 업로드 테스트 pr 겸 ci 수정
- ci에서 push 트리거 삭제
=> [CP-38] s3 jar zip 업로드 테스트 pr

.github/workflows/deploy.yml, src/main/java/com/pet/Application.java
=> [CP-40] S3 Code Deploy 문서 수정

appspec.yml, deploy.sh
close #43
- 설명 : code deploy appspec.yml 및 deploy.sh 파일 추가
- change
=> [CP-43] chore: CD 파일 설정

.github/workflows/deploy.yml
close #
- 설명 : code deploy 트리거 작성
- change
=> [CP-42] chore: github action code deploy 트리거 생성

.github/workflows/deploy.yml
close #46 
- 설명 : deploy 명령어에 개행 추가
- change
=> [CP-46] fix: 개행 추가

src/main/java/com/pet/domains/account/controller/AccountController.java
close #48 
- 설명 : test 위한 health check api 추가
- change
=> [CP-48] feat: 서버 확인용 health check api 추가

.github/workflows/deploy.yml
close 
- 설명 : 배포 실패 버그
- s3 location key 수정
=> [CP-50] fix: location key 수정

.github/workflows/deploy.yml
close #
- 설명 : 배포 버그
- key값 수정 2
=> [CP-50] fix: location key 수정2

.github/workflows/deploy.yml, appspec.yml
close #
- 설명 : 파일 오타 및 경로 수정
- change
=> [CP-50] fix: 파일 오타 및 경로 수정

.github/workflows/deploy.yml, appspec.yml
=> [CP-50] code deploy 패턴 수정

.github/workflows/deploy.yml, appspec.yml, deploy.sh, src/main/java/com/pet/domains/HealthCheckController.java, src/main/java/com/pet/domains/account/controller/AccountController.java
close #50 
- 설명 : asspec.yml 오타 수정 및 health check api 수정
- asspec.yml 오타 수정 및 health check api 수정
=> [CP-50 ] 배포 마지막 수정 

.github/workflows/deploy.yml, .github/workflows/gradle.yml
Reverts prgrms-web-devcourse/Team_i6_comepet_BE#59
=> Revert "[CP-57] chore: CI/CD 통합"

build.gradle
=> [CP-67] chore: apache commons lang 패키지로 수정

src/main/java/com/pet/domains/statistics/domain/PostStatistics.java
close #66 
- 설명 :  LocalDateTime으로 수정
- PostStatistics date 필드 수정
=> [CP-66] feat: date LocalDateTime으로 수정

src/main/java/com/pet/domains/account/domain/Account.java, src/main/java/com/pet/domains/image/domain/Image.java, src/main/java/com/pet/domains/post/domain/MissingPostImage.java
close #60 
- 설명 : Image 테이블 ERD 수정에 따라 엔티티를 수정하였습니다.
- change
=> [CP-60] feat: Image 테이블 변경에 따른 엔티티 수정

build.gradle
close #89 
- 설명 : fix: api docs do first로 기존 파일 삭제
- gradle task 추가
=> [CP-89] fix: api docs do first로 기존 파일 삭제

.github/workflows/deploy.yml, build.gradle, src/main/resources/application.yaml
close #
- 설명 : [CP-91] fix: 포트 수정 및 clean build
- change
=> [CP-91] fix: 포트 수정 및 clean build

.github/workflows/deploy.yml, build.gradle, src/main/resources/application.yaml
close #
- 설명 : index.html 추가
- index.html 추가
=> [CP-91] index.html 추가

src/main/java/com/pet/common/config/WebMvcConfig.java
close #97 
- 설명 : cors 해제
- web config 클래스 오버리이딩
=> [CP-97] fix: cors 풀기

src/main/java/com/pet/domains/post/domain/MissingPostBookmark.java, src/main/java/com/pet/domains/post/domain/ShelterPostBookmark.java
close #102
- 설명 : 오전에 토의한대로 post 패키지 하위로 이동했습니다.
- bookmark package 삭제
=> [CP-102] chore: post 패키지로 이동

src/main/java/com/pet/domains/account/controller/AccountController.java, src/main/java/com/pet/domains/account/dto/request/AccountCreateParam.java, src/main/java/com/pet/domains/account/dto/request/AccountUpdateParam.java, src/main/java/com/pet/domains/post/controller/MissingPostController.java, src/main/java/com/pet/domains/post/dto/request/MissingPostCreateParam.java, src/main/java/com/pet/domains/post/dto/request/MissingPostUpdateParam.java, src/test/java/com/pet/domains/account/controller/AccountControllerTest.java, src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
close #100 
- 설명 : feat: 이미지 요청 로깅 추가
- change
=> [CP-100] feat: 이미지 요청 로깅 추가

src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java, src/test/java/com/pet/domains/post/controller/ShelterPostControllerTest.java
close #
- 설명 : token이 필요없는 api의 명세를 수정하였습니다.
- change
=> [CP-109] docs: 게시물 조회 토큰 삭제 및 access header 추가

src/main/java/com/pet/domains/auth/domain/Group.java
=> [CP-117]fix: 디비 네이밍 수정

src/main/java/com/pet/common/config/InitDataConfig.java, src/main/java/com/pet/common/config/SecurityConfig.java, src/main/java/com/pet/common/config/WebMvcConfig.java, src/main/java/com/pet/domains/account/controller/AccountController.java, src/main/java/com/pet/domains/account/domain/Account.java, src/main/java/com/pet/domains/account/service/AccountService.java, src/main/java/com/pet/domains/auth/repository/GroupRepository.java, src/main/java/com/pet/domains/auth/repository/PermissionRepository.java
=> [CP-119]fix: cors문제 및 패스워드 인증 문제 수정

src/main/java/com/pet/common/config/InitDataConfig.java, src/main/java/com/pet/common/config/WebMvcConfig.java, src/main/java/com/pet/common/exception/AuthenticationException.java, src/main/java/com/pet/common/exception/GlobalExceptionHandler.java, src/main/java/com/pet/domains/account/controller/AccountController.java, src/main/java/com/pet/domains/account/domain/Account.java, src/main/java/com/pet/domains/account/domain/LoginAccount.java, src/main/java/com/pet/domains/account/service/AccountService.java, src/main/java/com/pet/domains/auth/HandlerMethodResolverArgumentConfig.java, src/main/java/com/pet/domains/auth/controller/argumentresolver/JwtAuthenticationArgumentResolver.java, src/test/java/com/pet/domains/account/WithAccount.java, src/test/java/com/pet/domains/account/WithAccountSecurityContextFactory.java, src/test/java/com/pet/domains/account/controller/AccountControllerTest.java, src/test/java/com/pet/domains/docs/BaseDocumentationTest.java
=> [CP-123] feat: Jwt Mocking Test, jwt 토큰 인증 및 회원 객체 조회 관심 분리

src/main/java/com/pet/domains/account/controller/AccountController.java, src/main/java/com/pet/domains/account/service/AccountService.java, src/main/java/com/pet/domains/auth/service/AuthenticationService.java, src/test/java/com/pet/domains/account/controller/AccountControllerTest.java, src/test/java/com/pet/domains/docs/BaseDocumentationTest.java
=> [CP/126] fix: 빈 순환참조 해결

src/main/java/com/pet/Application.java, src/main/java/com/pet/domains/area/domain/City.java, src/main/java/com/pet/domains/area/dto/request/CityCreateParams.java, src/main/java/com/pet/domains/area/dto/response/CityApiPageResults.java, src/main/java/com/pet/domains/area/mapper/CityMapper.java, src/main/java/com/pet/domains/area/repository/CityRepository.java, src/main/java/com/pet/domains/area/service/CityService.java, src/main/java/com/pet/domains/post/service/ShelterApiService.java, src/main/resources/application.yml
close #131 
- 설명 : 시도 open api 서비스 추가 & data migrate
- xml 파싱 dto  클래스 추가
- mapper 클래스 추가
- 스케줄러 사용
- saveCities cron 메서드는 데이터 최초로 넣어지고 어노테이션 삭제하겠습니다.
- 플라이웨이를 이용하면? 이런 애매한 초기화 작업을 관리할 수 있을 것 같네요 ㅠ
=> [CP-131] feat: 시도 open api 서비스 추가 & data migrate

src/main/java/com/pet/domains/account/domain/SignEmail.java, src/main/java/com/pet/domains/account/repository/SignEmailRepository.java, src/main/java/com/pet/domains/account/service/AccountService.java
close #
- 설명 : ㅜㅜㅜㅜㅜㅜㅜㅜㅜ
- change
=> [CP-136] DDL 문제 수정

src/main/java/com/pet/Application.java, src/main/java/com/pet/domains/post/service/ShelterApiService.java
close #140 
- 설명 :  스프링 애플리케이션 타임존 설정
=> [CP-140] 스프링 애플리케이션 타임존 설정

src/main/java/com/pet/domains/post/domain/ShelterPost.java, src/main/java/com/pet/domains/post/service/ShelterService.java, src/main/resources/application-dev.yml
close #147 
- 설명 : shelter post nullable 하도록 수정
api 의존적인 데이터인 보호소 게시글 필드들을 널 허용하도록 수정했습니다.
- 로그 수정
=> [CP-147] shelter post 필드들 nullable 하도록 수정

build.gradle, src/main/java/com/pet/common/config/SecurityConfig.java, src/main/java/com/pet/common/exception/ExceptionMessage.java, src/main/java/com/pet/common/oauth2/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/pet/domains/account/domain/Account.java, src/main/java/com/pet/domains/account/service/AccountService.java, src/main/java/com/pet/domains/auth/oauth2/GoogleUser.java, src/main/java/com/pet/domains/auth/oauth2/Oauth2User.java, src/main/java/com/pet/domains/auth/oauth2/ProviderType.java, src/main/java/com/pet/domains/image/domain/Image.java, src/main/resources/application.yml, src/test/java/com/pet/domains/account/WithAccountSecurityContextFactory.java
close #134 
- 설명 : 핸들러를 통해 소셜로그인이 성공된다면 토큰을 발급합니다.
- change
=> [CP-134] feat: 구글, 네이버 로그인

lombok.config, src/main/java/com/pet/common/exception/ExceptionMessage.java, src/main/java/com/pet/domains/animal/domain/Animal.java, src/main/java/com/pet/domains/animal/domain/AnimalKind.java, src/main/java/com/pet/domains/post/controller/ShelterPostController.java, src/main/java/com/pet/domains/post/domain/ShelterPostBookmark.java, src/main/java/com/pet/domains/post/repository/ShelterPostBookmarkRepository.java, src/main/java/com/pet/domains/post/service/ShelterApiService.java, src/main/java/com/pet/domains/post/service/ShelterPostBookmarkService.java, src/main/java/com/pet/domains/post/service/ShelterPostService.java, src/test/java/com/pet/domains/animal/service/AnimalServiceTest.java, src/test/java/com/pet/domains/docs/BaseDocumentationTest.java, src/test/java/com/pet/domains/post/controller/ShelterPostControllerTest.java, src/test/java/com/pet/domains/post/service/ShelterPostBookmarkServiceTest.java
close #152 
- 설명 : 보호소 게시글 북마크 등록 api 추가
- 롬복 커버리지 반영 x
- 엔티티 생성시 널 체크 및 테스트 코드 추가
- 매퍼를 이용한 부분은 어떻게 서비스 단위테스트를 작성해야할까요? 다 mocking을 해야하나..
변환 부분은 실제 인스턴스로 하고 싶은데 @ Spy가 안먹히네요 ㅠㅠ
=> [CP-152] 보호소 게시글 북마크 등록 api 추가

src/main/resources/application.yml
=> [CP-160] chore: sql 쿼리 로그 남기기

src/main/java/com/pet/common/config/InitDataConfig.java, src/main/java/com/pet/domains/account/controller/AccountController.java, src/main/java/com/pet/domains/account/domain/SignEmail.java, src/main/java/com/pet/domains/account/dto/request/AccountSignUpParam.java, src/main/java/com/pet/domains/account/service/AccountService.java, src/main/java/com/pet/infra/HtmlMailSender.java, src/test/java/com/pet/domains/account/controller/AccountControllerTest.java, src/test/java/com/pet/domains/account/repository/SignEmailRepositoryTest.java
=> [CP-159] 이메일 전송 문제

src/main/java/com/pet/domains/image/domain/PostImage.java, src/main/java/com/pet/domains/post/service/MissingPostService.java, src/main/java/com/pet/domains/tag/domain/PostTag.java, src/main/java/com/pet/domains/tag/domain/Tag.java
close #182 
- 설명 : 잘못된 매개변수와 null 체크를 추가하였습니다.
- change
=> [CP-182] fix: 실종/보호 게시물 Service bug 해결

README.md
close #
- 설명 : 리드미 초안입니당
- change
=> [CP-185] docs: README 초안 작성

src/main/java/com/pet/domains/comment/controller/CommentController.java, src/main/java/com/pet/domains/comment/domain/Comment.java, src/main/java/com/pet/domains/comment/repository/CommentRepository.java, src/main/java/com/pet/domains/comment/service/CommentService.java, src/test/java/com/pet/domains/comment/controller/CommentControllerTest.java, src/test/java/com/pet/domains/comment/repository/CommentRepositoryTest.java, src/test/java/com/pet/domains/post/repository/MissingPostRepositoryTest.java
close #201 
- 설명 : 댓글 삭제 api 구현
- change
=> [CP-201] 댓글 삭제 api 구현

src/main/java/com/pet/common/exception/controller/ExceptionController.java
close #210 
- 설명 : 프론트에게 동적으로 메세지 안내하기 위해 생성했습니다.
- change
=> [CP-210] 에러 응답 안내 api

src/main/java/com/pet/domains/area/controller/CityController.java, src/main/java/com/pet/domains/area/domain/City.java, src/main/java/com/pet/domains/area/mapper/CityMapper.java, src/main/java/com/pet/domains/area/repository/CityRepository.java, src/main/java/com/pet/domains/area/service/CityService.java, src/main/java/com/pet/domains/area/service/TownService.java, src/test/java/com/pet/domains/area/controller/CityControllerTest.java, src/test/java/com/pet/domains/area/repository/CityRepositoryTest.java, src/test/java/com/pet/domains/docs/BaseDocumentationTest.java
close #209 
- 설명 : 타운과 시티가 다대일 관계에서 findall을 해오는데 시티쪽에서 전체조회해도 괜찮은지 궁금합니당!
쿼리는 요롷게 나옵니다!
- change
=> [CP-209] feat: 시도/시군구 조회 api

src/docs/asciidoc/index.adoc, src/main/java/com/pet/domains/account/controller/AccountController.java, src/main/java/com/pet/domains/account/dto/response/AccountReadResult.java, src/main/java/com/pet/domains/account/mapper/AccountMapper.java, src/main/java/com/pet/domains/account/service/AccountService.java, src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
close #214 
- 설명 : 회원 정보 조회 api
- change
=> [CP-214] feat: 회원 정보 조회 api

src/main/java/com/pet/common/config/SecurityConfig.java, src/main/java/com/pet/domains/animal/domain/Animal.java, src/main/java/com/pet/domains/animal/domain/AnimalKind.java, src/main/java/com/pet/domains/area/domain/City.java, src/main/java/com/pet/domains/area/domain/Town.java, src/main/java/com/pet/domains/post/domain/MissingPostBookmark.java, src/main/java/com/pet/domains/post/domain/ShelterPostBookmark.java
close #225 
- 설명 : 안전성을 위해 유니크 제약조건 추가했습니다!
=> [CP-225] 유니크 제약조건 추가

src/docs/asciidoc/index.adoc, src/main/java/com/pet/common/config/SecurityConfig.java, src/main/java/com/pet/domains/account/controller/AccountController.java, src/main/java/com/pet/domains/account/domain/Account.java, src/main/java/com/pet/domains/account/service/AccountService.java, src/main/java/com/pet/infra/EmailMessage.java, src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
=> [CP-222] 임시 비밀번호 전송 api

src/main/java/com/pet/domains/account/controller/AccountController.java, src/main/java/com/pet/domains/account/dto/response/AccountReadResult.java, src/main/java/com/pet/domains/account/mapper/AccountMapper.java, src/main/java/com/pet/domains/account/repository/AccountRepository.java, src/main/java/com/pet/domains/account/service/AccountService.java, src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
close #228 
- 설명 : 이미지가 없을 수도 있어서 left join으로 조회했습니다!
- change
=> [CP-228] feat: 회원 조회 이미지 추가 조회

.github/workflows/deploy.yml, src/main/java/com/pet/common/config/WebMvcConfig.java
=> [CP-241] CORS 이슈 수정

src/main/java/com/pet/common/config/SecurityConfig.java
=> [CP-243] fix: options 허용

src/main/java/com/pet/common/exception/ExceptionMessage.java, src/main/java/com/pet/domains/account/controller/NotificationController.java, src/main/java/com/pet/domains/account/domain/Notification.java, src/main/java/com/pet/domains/account/repository/NotificationRepository.java, src/main/java/com/pet/domains/account/service/NotificationService.java, src/test/java/com/pet/domains/account/repository/NotificationRepositoryTest.java
=> [CP-223] feat: 알림 클릭 api

src/main/java/com/pet/domains/animal/domain/Animal.java, src/main/java/com/pet/domains/animal/domain/AnimalKind.java, src/main/java/com/pet/domains/area/domain/Town.java
close #257
- 설명 : 유니크 이슈 수정
- change
=> [CP-257] 유니크 이슈 수정

src/main/java/com/pet/domains/image/domain/PostImage.java, src/main/java/com/pet/domains/post/domain/MissingPost.java, src/main/java/com/pet/domains/post/service/MissingPostService.java, src/test/java/com/pet/domains/post/repository/MissingPostRepositoryTest.java
close #256 
- 설명 : 연관관계를 수정했습니다.
- change
=> [CP-256] 실종/보호 게시물 Entity 연관관계 수정

src/main/java/com/pet/domains/post/controller/MissingPostController.java, src/main/java/com/pet/domains/post/repository/MissingPostRepository.java, src/main/java/com/pet/domains/post/service/MissingPostService.java, src/test/java/com/pet/domains/post/service/MissingPostServiceTest.java
=> [CP-265] fix: 실종/보호 게시물 저장 에러 수정

src/main/java/com/pet/domains/account/controller/NotificationController.java, src/main/java/com/pet/domains/account/dto/response/NotificationReadResults.java, src/main/java/com/pet/domains/account/mapper/NotificationMapper.java, src/main/java/com/pet/domains/account/repository/NotificationRepository.java, src/main/java/com/pet/domains/account/service/NotificationService.java, src/test/java/com/pet/domains/account/controller/NotificationControllerTest.java
close #284 
- 설명 : 나의 알림만 조회하도록 수정 & 응답 포맷 추가
- 로직이 전체 알림이 조회가능하도록 되어있던 것 같아요 수정했습니다!!
=> [CP-284] 나의 알림만 조회하도록 수정 & 응답 포맷 추가

src/main/java/com/pet/domains/account/dto/response/NotificationReadResults.java, src/main/java/com/pet/domains/account/mapper/NotificationMapper.java, src/test/java/com/pet/domains/account/controller/NotificationControllerTest.java
close #291 
- 설명 : 알림 조회 응답 필드 누락 수정
- change
=> [CP-291] 알림 조회 응답 필드 누락 수정

src/main/java/com/pet/domains/account/dto/response/NotificationReadResults.java, src/main/java/com/pet/domains/account/service/NotificationService.java, src/test/java/com/pet/domains/account/controller/NotificationControllerTest.java
=> [CP-293] feat: 알림 조회시 id도 조회되도록 수정

src/docs/asciidoc/index.adoc, src/main/java/com/pet/domains/account/controller/NotificationController.java, src/main/java/com/pet/domains/account/repository/NotificationRepository.java, src/main/java/com/pet/domains/account/service/NotificationService.java, src/test/java/com/pet/domains/account/controller/NotificationControllerTest.java
close #
- 설명 : delete all in batch로 알림을 모두 삭제하는데 문제없겠죠?
- change
=> [CP-298] 알림 전체 삭제

src/main/java/com/pet/domains/post/dto/request/MissingPostCreateParam.java
close #303 
- 설명 : bean validation 메시지 오타 수정
- change
=> [CP-303] bean validation 메시지 오타 수정

deploy-dev.sh, src/main/java/com/pet/common/config/CustomPageableConfiguration.java, src/main/java/com/pet/domains/post/repository/MissingPostCustomRepositoryImpl.java, src/main/java/com/pet/domains/post/repository/ShelterPostCustomRepositoryImpl.java
close #309 
- 설명 : offset 이슈 수정
- 페이징을 쉽게해주는 서포트 추가
@
=> [CP-309] fix: offset 이슈 수정

src/main/java/com/pet/domains/account/mapper/AccountMapper.java
close #314 
- 설명 : mapstruct에서 값이 바뀌게 설정했습니다ㅜ
- change
=> [CP-314] fix: city, town 바뀐 이슈 수정

src/main/java/com/pet/domains/post/service/MissingPostService.java
=> [CP-316] 실종/보호 게시물 수정 이슈 해결

src/main/java/com/pet/domains/post/dto/response/ShelterPostReadResult.java, src/test/java/com/pet/domains/post/controller/ShelterPostControllerTest.java
close #317 
- 설명 : 보호소 게시글 보호 장소 응답  필드 추가
- change
=> [CP-317] 보호 장소 응답  필드 추가

src/main/java/com/pet/domains/account/domain/Account.java
=> fix: password nullable하게 수정

src/main/java/com/pet/domains/account/service/AccountService.java
close #
- 설명 : 둘 다 false인 경우도 예외로 처리하였습니다
- change
=> [CP-324] fix: 디폴트 지역이 둘다 false인 경우 예외처리

src/main/java/com/pet/domains/image/domain/Image.java
=> [CP-326] feat: image 테이블 baseentity 상속 추가

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, deploy-dev.sh, deploy-prod.sh, src/main/resources/application-prod.yml
close #323 
- 설명 : Ec2 인스턴스가 하나인 상황으로 인해 dev는 이제 승인이 없으면 배포되지 않도록 수정했습니다.
- yml & sh 수정
=> [CP-323] ec2 main으로 배포되도록 수정

src/main/java/com/pet/infra/HtmlMailSender.java
=> [CP-330] feat: profile prod 추가

build.gradle, src/main/resources/logback.xml
close #332 
- 설명 :  클라우드 와치 로그 전송
- change
=> [CP-332] 클라우드 와치 로그 전송

src/main/resources/logback.xml
=> feat: 필터 추가

src/main/java/com/pet/common/oauth2/OAuth2AuthenticationSuccessHandler.java
=> [CP-336] test: oauth test

src/main/resources/application-dev.yml, src/main/resources/application-prod.yml
=> [CP-339] fix: DB DATE 0 문제 수정

build.gradle, src/main/java/com/pet/Application.java, src/main/java/com/pet/common/aop/RequestLoggingAspect.java, src/main/java/com/pet/common/config/InitDataConfig.java, src/main/java/com/pet/domains/account/service/NotificationAsyncService.java, src/main/java/com/pet/domains/post/controller/MissingPostController.java, src/main/java/com/pet/domains/post/service/MissingPostService.java, src/main/java/com/pet/domains/post/service/ShelterApiService.java
=> [CP-307] feat: 모든 요청 Aop 로그 처리

src/main/java/com/pet/domains/tag/domain/Tag.java
close #343 
- 설명 : 태그 엔티티 네임에 인덱스 추가
=> [CP-343] 태그 엔티티 네임에 인덱스 추가

src/main/resources/logback.xml
close #345 
- 설명 : 로그 스트림 포맷 변경
- change
=> [CP-345] 로그 스트림 포맷 변경

src/main/java/com/pet/common/oauth2/OAuth2AuthenticationSuccessHandler.java, src/main/resources/logback.xml
close #352 
- 설명 : 슬랙 에러 로그 & 로그백 수정
- change
=> [CP-350] 리다이렉트&슬랙 수정

src/main/java/com/pet/common/config/RedisCachingConfig.java, src/main/java/com/pet/common/config/RedisConfig.java, src/main/java/com/pet/common/oauth2/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/pet/common/s3/service/FileUploadService.java, src/main/java/com/pet/common/s3/validator/ImageContentTypeValidator.java, src/main/java/com/pet/common/s3/validator/ImageFileValidator.java, src/main/java/com/pet/common/s3/validator/ValidImage.java, src/main/java/com/pet/infra/ConsoleEmailSender.java, src/main/resources/application-rds.yml
=> [CP-348] feat: image validation 추가

src/main/java/com/pet/domains/post/controller/MissingPostController.java, src/main/java/com/pet/domains/post/domain/MissingPost.java, src/main/java/com/pet/domains/post/service/MissingPostService.java, src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
close #355 
- 설명 :
- change
특정 게시글 첫 조회 요청
동일 조회 요청
다른 게시글 요청 case
그 _는 예전 포맷인데 로컬이라 남아있어서 그렇습니다
=> [CP-355] 쿠키로 조회수 중복으로 증가하지 않도록 수정

src/main/java/com/pet/domains/post/controller/MissingPostController.java
close #357 
- 설명 : 쿠키 시큐어 설정
- change
=> [CP-356] 쿠키 시큐어 설정

src/main/java/com/pet/common/exception/ExceptionHandlerAdvice.java, src/main/java/com/pet/domains/account/domain/Provider.java
=> [CP-259] Feature/359

src/main/java/com/pet/domains/post/repository/MissingPostCustomRepository.java, src/main/java/com/pet/domains/post/repository/MissingPostCustomRepositoryImpl.java, src/main/java/com/pet/domains/post/repository/ShelterPostCustomRepository.java, src/main/java/com/pet/domains/post/repository/ShelterPostCustomRepositoryImpl.java, src/main/java/com/pet/domains/post/repository/projection/MissingPostWithFetch.java, src/main/java/com/pet/domains/post/repository/projection/ShelterPostWithFetch.java, src/main/java/com/pet/domains/post/service/MissingPostService.java, src/main/java/com/pet/domains/post/service/ShelterPostService.java, src/main/resources/logback.xml, src/test/java/com/pet/domains/post/service/MissingPostServiceTest.java
close #361 
- 설명 : 북마크 게시글 이슈 수정
- change
=> [CP-361] 북마크 게시글 이슈 수정

src/main/java/com/pet/domains/post/service/MissingPostService.java
=> [CP-363] fix: 게시물 수정시 품종 getOrCreate로 변경

src/main/java/com/pet/domains/post/repository/MissingPostCustomRepositoryImpl.java
close #365 
- 설명 : 작성날짜로 필터링되어야 해서 수정했습니다.
- change
=> [CP-365] 실종 게시글 날짜 필터링 이슈 수정

src/main/java/com/pet/domains/post/repository/MissingPostCustomRepositoryImpl.java
close #
- 설명 : localdate to time 변환 에러 수정
- change
=> [CP-366] 컨버트 이슈 수정

src/main/java/com/pet/common/oauth2/OAuth2AuthenticationSuccessHandler.java
close #
- 설명 : 프론트 서버로 전달되도록 수정했습니다.
- change
=> [CP-367] feat: oauth2 리다이렉트 프론트 서버로 가도록 수정

src/main/java/com/pet/domains/post/repository/MissingPostCustomRepositoryImpl.java, src/main/java/com/pet/domains/post/repository/ShelterPostCustomRepositoryImpl.java
close #370 
- 설명 : start date를 지정한 경우 최신순으로 나오면 어색한 감이 있어서 수정했습니다.
- change
=> [CP-370] start 포함 검색인 경우 날짜 오름차순 정렬

src/main/java/com/pet/domains/post/domain/MissingPost.java, src/main/resources/application-prod.yml
close #372 
- 설명 : 다이나믹 업데이트 추가
- change
=> [CP-372] 다이나믹 업데이트 추가

README.md
=> [CP-374] feat: readme 2차안 작성

src/main/java/com/pet/domains/account/repository/AccountRepository.java, src/main/java/com/pet/domains/account/service/NotificationAsyncService.java, src/main/java/com/pet/domains/post/service/MissingPostService.java, src/test/java/com/pet/domains/account/repository/AccountRepositoryTest.java
close #379 
- 설명 : 자신이 쓴 글에는 알림이 안오도록 수정
- 쿼리 수정
=> [CP-379] 자신이 쓴 글에는 알림이 안오도록 수정

README.md
close #
- 설명 : 시연 gif 추가
- change
=> [CP-281] docs: gif 추가

README.md
close #384 
- 설명 : 리드미에 docs 추가
- change
=> [CP-384] 리드미에 docs 추가

README.md
=> [CP-381] git 수정
